//
// Generated By:JAX-WS RI 2.2.10 (JAXB RI IBM IBM 2.2.10-06/29/2016 1:04:38 PMforeman-)
//


package db_emulator.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "createProductDB_Object", namespace = "http://db_emulator/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createProductDB_Object", namespace = "http://db_emulator/")
public class CreateProductDB_Object {


}
