//
// Generated By:JAX-WS RI 2.2.10 (JAXB RI IBM IBM 2.2.10-06/29/2016 1:04:38 PMforeman-)
//


package lamm_hello_world.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "getProductObjectResponse", namespace = "http://lamm_hello_world/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getProductObjectResponse", namespace = "http://lamm_hello_world/")
public class GetProductObjectResponse {

    @XmlElement(name = "return", namespace = "")
    private lamm_hello_world.LamM_HelloWorld _return;

    /**
     * 
     * @return
     *     returns LamM_HelloWorld
     */
    public lamm_hello_world.LamM_HelloWorld getReturn() {
        return this._return;
    }

    /**
     * 
     * @param _return
     *     the value for the _return property
     */
    public void setReturn(lamm_hello_world.LamM_HelloWorld _return) {
        this._return = _return;
    }

}
